id = "d"
name = "D"
description = "D language support"
version = "0.0.1"
schema_version = 1
authors = ["ryuukk <ryuukk.dev@gmail.com>"]
repository = "https://github.com/ryuukk/dls"

[language_servers.dls]
name = "dls"
language = "D"

[grammars.d]
repository = "https://github.com/gdamore/tree-sitter-d"
commit = "750dde90ed9cdbd82493bc28478d8ab1976b0e9f"
